# Generated by Django 5.1 on 2024-08-30 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(max_length=50)),
                ('product_Cost', models.BigIntegerField()),
                ('product_Discount', models.BigIntegerField(blank=True, null=True)),
                ('product_Color', models.CharField(max_length=50)),
                ('delivery_Address', models.CharField(max_length=80)),
                ('product_Highlight', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'MobileProductDetail',
                'verbose_name_plural': 'MobileProductDetails',
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highLights_Rom', models.CharField(max_length=50)),
                ('highLights_Ram', models.CharField(max_length=50)),
                ('highLights_Display', models.CharField(max_length=50)),
                ('highLights_Cemara', models.CharField(max_length=50)),
                ('highLights_Battery', models.CharField(max_length=50)),
                ('highLights_Processor', models.CharField(max_length=50)),
                ('highLights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='hub.mobileproductdetail')),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_House_No', models.CharField(max_length=60)),
                ('delivery_Street', models.CharField(max_length=60)),
                ('delivery_City', models.CharField(max_length=60)),
                ('delivery_Pin_Code', models.CharField(max_length=60)),
                ('delivery_State', models.CharField(max_length=60)),
                ('delivery_Country', models.CharField(max_length=60)),
                ('delivery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='hub.mobileproductdetail')),
            ],
            options={
                'verbose_name': 'Delivary',
                'verbose_name_plural': 'Delivaries',
            },
        ),
    ]
