# Generated by Django 5.1 on 2024-08-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_mobileproductdetail_highlight_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileproductdetail',
            name='product_Image',
            field=models.ImageField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
